name:                qubism
version:             0.1.0.0
github:              "qubitrot/qubism"
license:             MIT
author:              "Keith Pearson"
maintainer:          "keith@qubitrot.org"
copyright:           "2018 Keith Pearson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/qubitrot/qubism#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- singletons
- finite-typelits
- ghc-typelits-knownnat
- MonadRandom
- hmatrix
- vector
- containers
- hspec
- QuickCheck
- quickcheck-properties
- megaparsec >= 7.0.0
- parser-combinators
- text
- filepath

library:
  source-dirs: src

executables:
  qubism:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - qubism

tests:
  qubism-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - qubism
